PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT *
FROM <http://data.open.ac.uk/context/podcast>
FROM <http://data.open.ac.uk/context/openlearn2>
FROM <http://data.open.ac.uk/context/videofinder>
WHERE {
  VALUES ?type {<http://data.open.ac.uk/openlearn/ontology/OpenLearnArticle>  <http://data.open.ac.uk/podcast/ontology/VideoPodcast>  <http://data.open.ac.uk/podcast/ontology/AudioPodcast>  <http://data.open.ac.uk/videofinder/ontology/VideofinderObject> } .
  ?id a ?type .
} 