PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT *
FROM <http://data.open.ac.uk/context/xcri>
WHERE {
  ?id a <http://purl.org/net/mlo/LearningOpportunitySpecification> .
} 