PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX bds: <http://www.bigdata.com/rdf/search#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
	?entity rdf:type ?type .
	?entity rdfs:label ?lit .
	?entity bds:relevance ?score .
	?entity dcterms:title ?title .
	?entity foaf:name ?name .
	?entity skos:prefLabel ?pLabel .
	?entity dcterms:description ?description .
	?entity rdfs:comment ?comment .
} 
FROM <http://data.open.ac.uk/context/xcri>
WHERE {
    
	?lit bds:search "history" .
	?lit bds:matchAllTerms true .
	?lit bds:relevance ?score .
    ?entity a <http://purl.org/net/mlo/LearningOpportunitySpecification> .
	{ ?entity rdfs:label ?lit } 
	UNION 
	{ ?entity ?relatedTo [ rdfs:label ?lit ] . } 
	UNION 
	{ [ rdfs:label ?lit; ?relatedTo	?entity ] . } .
    ?entity ?predicate ?value
} ORDER BY DESC(?score)