#+ endpoint: http://data.open.ac.uk/sparql
#+ defaults:
#+   - search: history
#+ transform: {
#+     "course": "?entity",
#+     "type": "?type",
#+     "genre": "?genre",
#+     "score": "?score",
#+     "title": "?title",
#+     "?predicate": "?value",
#+     "$anchor": "course"
#+   }

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX bds: <http://www.bigdata.com/rdf/search#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT
	?entity
    ?type 
	 ?lit 
	 ?score 
	 ?title 
	 ?name 
     ?predicate
     ?value
} 
FROM <http://data.open.ac.uk/context/xcri>
WHERE {
    
	?lit bds:search ?_search_xsd_string .
	?lit bds:matchAllTerms true .
	?lit bds:relevance ?score .
    ?entity a <http://purl.org/net/mlo/LearningOpportunitySpecification> .
	{ ?entity rdfs:label ?lit } 
	UNION 
	{ ?entity ?relatedTo [ rdfs:label ?lit ] . } 
	UNION 
	{ [ rdfs:label ?lit; ?relatedTo	?entity ] . } .
    ?entity ?predicate ?value
} ORDER BY DESC(?score)