PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX bds: <http://www.bigdata.com/rdf/search#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
	?entity rdf:type ?type .
	?entity rdfs:label ?lit .
	?entity bds:relevance ?score .
    ?entity ?property ?value .
} 
FROM <http://data.open.ac.uk/context/podcast>
FROM <http://data.open.ac.uk/context/openlearn2>
FROM <http://data.open.ac.uk/context/videofinder>
WHERE {
    
	?lit bds:search "history" .
	?lit bds:matchAllTerms true .
	?lit bds:relevance ?score .

		{ ?entity rdfs:label ?lit } 
		UNION 
		{ ?entity ?relatedTo [ rdfs:label ?lit ] . } 
		UNION 
		{ [ rdfs:label ?lit; ?relatedTo	?entity ] . } 
		?entity a ?type .
    	FILTER (?type in (<http://data.open.ac.uk/openlearn/ontology/OpenLearnArticle>, <http://data.open.ac.uk/podcast/ontology/VideoPodcast>, <http://data.open.ac.uk/podcast/ontology/AudioPodcast>, <http://data.open.ac.uk/videofinder/ontology/VideofinderObject> ))
		?entity ?property ?value
} ORDER BY DESC(?score) ?entity